server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=UTC
    username: root
    password: "root@123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 40
      max-wait: 6000
      stat-view-servlet.enabled: false
      web-stat-filter.enabled: false
      filter.config.enabled: false
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址
        cluster-name: BD # 集群名称

logging:
  level:
    com.zhangxiaofanfan: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
