spring:
  redis:
    database: 0
    password: toos
    port: 8637
    host: 10.138.44.107
    lettuce:
      shutdown-timeout: 100ms
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms