# 服务端口号
server:
  port: 8000

spring:
  active: dev # 默认开启 dev 场景

  application:
    name: zxff-skywalking-gateway-service

  cloud:
    # nacos 注册中心配置
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev # 命名空间。这里使用 dev 开发环境

    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        # user-server 服务
        - id: zxff-skywalking-user-router
          uri: lb://zxff-skywalking-user-service
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/user/**
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        # order-server 服务
        - id: zxff-skywalking-order-router
          uri: lb://zxff-skywalking-order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs
        # product-server 服务
        - id: zxff-skywalking-product-router
          uri: lb://zxff-skywalking-product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/v3/api-docs, /v3/api-docs

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: zxff-skywalking-user-service
        service-name: zxff-skywalking-user-service
        url: /user/v3/api-docs
      - name: zxff-skywalking-order-service
        service-name: zxff-skywalking-order-service
        url: /order/v3/api-docs
      - name: zxff-skywalking-product-service
        service-name: zxff-skywalking-product-service
        url: /product/v3/api-docs

# 对外暴露监控端点配置
# springboot监控actuator
management:

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
  web:
    server:
      auto-time-requests: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
        step: 1ms
        descriptions: true

# 日志文件配置
logging:
  config: classpath:config/logback-spring.xml